package com.vaultpay.common.exception;

public enum ErrorCode {
    VALIDATION_ERROR,
    NOT_FOUND,
    CONFLICT,
    UNAUTHORIZED,
    INSUFFICIENT_FUNDS,
    RATE_LIMITED,
    ACCOUNT_LOCKED,
    PIN_LOCKED,
    BAD_REQUEST,
    INTERNAL_ERROR,
    DUPLICATE_TRANSACTION,
    TRANSACTION_IN_PROGRESS,
    WALLET_FROZEN,
    EXTERNAL_SERVICE_FAILURE,
    REVERSAL_FAILED
}

